#!/usr/bin/env bash
# Bash script to transfer file using scp
if [ $# -lt 3 ];
then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi
# get arguments in vars
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_KEY="$4"

scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$PATH_TO_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
# if [ -z "$4" ]; then
#    scp "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
# else
#    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$PATH_TO_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
# fi
