#!/usr/bin/env bash
# Bash script to transfer file using scp
if [ $# -lt 3 ];
then
echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
fi

# get arguments in vars
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_KEY="$4"

if [ -z "$4" ]; then
    scp "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
else
    scp -i "$PATH_TO_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi

