#!/usr/bin/env bash
# Bash script to install Nginx server
sudo apt update
sudo apt install nginx -y
sudo sed -i '53a location /redirect_me {\n return 301;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
