#!/usr/bin/env bash
# Bash script to install Nginx server
sudo apt update
sudo apt install nginx -y
file="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;
#    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    location /redirect_me {
        return 301;
    }
}"
echo "$file" |sudo  tee /etc/nginx/sites-available/default
sudo service nginx restart
