#!/usr/bin/env bash
# Bash script to install Nginx server
sudo apt update
sudo apt install nginx -y
#sudo sed -i '53a location / {\n return 404 "Ceci n'\''est pas une page";\n}' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
awk 'BEGIN {RS=""; ORS="\n"} {gsub(/[^#]location [^}]+}/, "\nlocation / {\n internal;\n}", $0); print}' /etc/nginx/sites-available/default  > temp_file && sudo mv temp_file /etc/nginx/sites-available/default
 awk 'BEGIN {RS=""; ORS="\n"} {gsub(/[^#]location [^}]+}/, "\n& \nerror_page 404 /error404.html;\n", $0); print}' /etc/nginx/sites-available/default  > temp_file && sudo mv temp_file /etc/nginx/sites-available/default
sudo service nginx restart
