#!/usr/bin/env bash
# Bash script to install Nginx server
sudo apt update
sudo apt install nginx -y
#sudo sed -i '53a location /redirect_me {\n return 301;\n}' /etc/nginx/sites-available/default
#awk 'BEGIN {RS=""; ORS="\n"} {gsub(/[^#]location [^}]+}/, "\nlocation /redirect_me {\n return 301;\n}", $0); print}' /etc/nginx/sites-available/default > temp_file && sudo mv temp_file /etc/nginx/sites-available/default
file="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
	try_files \$uri \$uri/ =404;
	add_header X-Served-By \$hostname;
    }
}"
echo "$file" |sudo  tee /etc/nginx/sites-available/default
sudo service nginx restart
