#!/usr/bin/env bash
# Bash script to install Nginx server
sudo apt update
sudo apt install nginx -y

file="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
    error_page 404 /error404.html;
    location /redirect_me {
        return 301;
    }
}"
sudo echo  "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
echo "$file" |sudo  tee /etc/nginx/sites-available/default
sudo service nginx restart
