#!/usr/bin/env bash
# Bash script to install HAproxy server
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy=2.8.\* -y

echo "
defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 521839-web-01  54.226.5.216:80 check
    server 521839-web-02  54.87.171.248:80 check"  | sudo  tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
