#!/usr/bin/env bash
# This script is displays "To infinity and beyond" indefinitely
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command";rm /var/run/myscript.pid;kill -9 $$' SIGTERM 
trap 'echo "Y U no love me?!"' SIGINT 
trap 'rm /var/run/myscript.pid;kill -9 $$' SIGQUIT 
while true
do
	echo "To infinity and beyond"
	sleep 2
done

