#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for i in $(seq 1 100)
do
	if [ $(( i % 3 )) -eq 0 ] || [ $(( i % 5)) -eq 0 ]
	then
		if [ $(( i % 3)) -eq 0 ]
		then
		echo -n "Fizz"
		fi

		if [ $((i % 5)) -eq 0 ]
		then
		echo -n "Buzz"
		fi
		echo ""
	else
		echo "$i"
	fi
		
done
export i
